#!/usr/bin/env python

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.gray()
import sys

from PIL import Image

try:
    output_file_path = sys.argv[1]
    titles = sys.argv[2::2]
    images = []
    for image_path in sys.argv[3::2]:
        images.append(Image.open(image_path))
except:
    print('Usage: {} <output file path> [<image 1 caption> <image 1 path> [<image 2 caption> <image 2 path>] ... ]'.format(sys.argv[0]))
    sys.exit(1)

for i, title in enumerate(titles):
    plt.subplot(1, len(images), i + 1)
    plt.title(title)
    plt.imshow(images[i])
    plt.axis('off')
plt.savefig(output_file_path)
